name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: ci
    runs-on: [self-hosted, ubuntu-20.04]
    strategy:
      matrix:
        image:
          - 'coqorg/coq:8.12.2'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - name: Submodule
        run: git submodule update --init
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'promising-hw.opam'
          custom_image: ${{ matrix.image }}
