name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: ci
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: avsm/setup-ocaml@v1
      - name: Coq
        run: opam install coq.8.13.1
      - name: Submodule
        run: git submodule update --init
      - name: Make
        run: make -j
      - name: Build
        run: ./build.sh
