name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

defaults:
  run:
    shell: bash

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.10.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Coq
        run: opam install coq.8.13.1

      - name: Submodule
        run: git submodule update --init

      - name: Make
        run: make -j

      - name: Build
        run: ./build.sh
