name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: ci
    runs-on: [self-hosted, ubuntu-20.04]
    strategy:
      matrix:
        coq_version:
          - '8.12.2'
          # - dev
        ocaml_version: ['4.11.1-flambda']
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          # opam_file: 'folder/coq-proj.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
      - name: Submodule
        run: git submodule update --init
      - name: Build
        run: ./build.sh
